Add Syntax API Code Gen related functionality into the extension
ballerina-platform/plugin-vscode-compiler-toolkit pull request #4
Opened 2021-04-16 07:13 UTC by kdsuneraavinash

## Purpose
$subject

## Goals
Add foundation files and a sample use case of integrating Syntax API code gen feature.
- A new command to copy the java code required to generate the current file to clipboard

## Approach
Add `vs-syntax-api-calls-gen` module and register its commands
Add syntax API code gen related functionality to language client
Add some tests

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-04-20 11:12 UTC, nadeeshaan requested changes

2021-04-20 11:12 UTC, nadeeshaan commented on package.json
> +                "title": "Copy Syntax-API Calls to Generate this Code",
Shall we use `Copy Syntax API calls to Clipboard` instead?

2021-04-20 11:21 UTC, SumayyaZiyad approved these changes
LGTM :)

2021-04-20 11:23 UTC, SumayyaZiyad commented on src/core/extended-language-client.ts
> +import {LanguageClient} from "vscode-languageclient";
The space between the curly braces and the imports are a convention we followed throughout the code base. Shall we stick to it?

2021-04-20 11:30 UTC, kdsuneraavinash commented
The CI seems to be pulling slp4 but since syntax API gen is not available in slp4 the tests are failing

2021-04-20 11:40 UTC, SumayyaZiyad commented
> The CI seems to be pulling slp4 but since syntax API gen is not available in slp4 the tests are failing

Had the same issue with the visualizer till slp4 was available. Based on the current workflow, until slp5 is available, I guess we will have to drop the tests on the main branch. 
At the same time, will also look into using a build from the master  instead.

2021-04-20 13:11 UTC, kdsuneraavinash commented
@SumayyaZiyad yeah, it should work with slp5
I disabled tests cases for now and opened #5

2021-04-20 13:25 UTC, SumayyaZiyad commented
> @SumayyaZiyad yeah, it should work with slp5
> I disabled tests cases for now and opened #5

The preview is available now right. So I can update the GH Actions to pull slp5 instead. If so we don't have to disable the test cases.
But we still have to manually keep updating the package being pulled - will try to figure out an alternative anyways. For now, will pull slp5. Sending a PR with the updated actions now.
Sorry about the mess :)

2021-04-20 17:17 UTC, SumayyaZiyad commented
> @SumayyaZiyad yeah, it should work with slp5
> I disabled tests cases for now and opened #5

Noted. Will re-enable the tests, once the approach to pulling the pack is figured out!

2021-04-21 05:32 UTC, nadeeshaan approved these changes
LGTM

2021-04-21 05:32 UTC, merged